export const PACKAGE_NAME = "@omni/database";
export { ensureDataDir, openDatabase, DATA_SUBDIRS } from "./connection.js";
export { MigrationManager, MigrationError } from "./migration/migration-manager.js";
export type { MigrationResult } from "./migration/migration-manager.js";
export { BaseRepository } from "./repositories/base.js";
export type { Entity } from "./repositories/base.js";
export { CollectionRepository } from "./repositories/collection.repository.js";
export { CommentRepository } from "./repositories/comment.repository.js";
export type { NewComment } from "./repositories/comment.repository.js";
export { UserRepository } from "./repositories/user.repository.js";
export type { CollectionRow, CommentRow, UserNoteRow } from "./types.js";
export { RuleCenter } from "./repositories/rule-center.js";
export { AIRepository } from "./repositories/ai.repository.js";
export type { NewSuggestion } from "./repositories/ai.repository.js";
export { FileRepository } from "./repositories/file.repository.js";
export type { NewLocalFile, NewFileIndex } from "./repositories/file.repository.js";
export { ContentGroupRepository } from "./repositories/content-group.repository.js";
export { TagRepository } from "./repositories/tag.repository.js";
export type { TagRow, CollectionTagRow } from "./repositories/tag.repository.js";
export { TopicRepository } from "./repositories/topic.repository.js";
export type { TopicRow } from "./repositories/topic.repository.js";
export type { ContentGroupRow } from "./repositories/content-group.repository.js";
export { AccountRepository } from "./repositories/account.repository.js";
export { SyncLogRepository } from "./repositories/sync-log.repository.js";
export type { NewSyncLog } from "./repositories/sync-log.repository.js";
